### ISSUE TITLE
Missing file,

### ISSUE THREAD

**Issue by PH-F** [EddieMachete/rhi-core-isncsci-algorithm#1]
Hi there!
I really like to try your code, but it looks like i'm misscing this file
/eddiemachete/em-core-isncsci-algorithm/em-core-isncsci-algorithm/em-core-isncsci-algorithm.html

**Comment by EddieMachete** [comment]
Hi Patrick.  I'm quite surprised you found the repository.  It is the first
time I get a message through GitHub.  I'm still working on the library.
Right now it does not perform a real calculation.  I think I can have the
algorithm ready by next week.  Would you want me to let you know when I
have the library working?

**Comment by PH-F** [comment]
Hello Eddie, Thank you for your quick reply!
It would be great If you could let me know when it's working.

Hope to hear from you soon.
Best, Patrick

**Comment by EddieMachete** [comment]
Hi Patrick, I got a good deal of coding done this week, but I was not able to complete the algorithm code this week, as I was hoping.  Tuesday would probably be a more likely date.  I'm very close. I'll keep you posted.

**Comment by PH-F** [comment]
Hi Eddy, thank you for keeping me posted!
I'm looking forward to the algorithm.

**Comment by EddieMachete** [comment]
Patrick, the algorithm works now.  I was able to successfully calculate our 83 test cases.  I'm keeping the code in beta because I have not completed the documentation, but the code works.  Right now, the best way to get an idea on how to use it is to look at the [unit tests](https://github.com/EddieMachete/rhi-core-isncsci-algorithm/blob/master/tests/rhi-core-isncsci-algorithm-tests.html).  I will be working on improving the examples and the code documentation.  Once I'm finished I'll mark the code as production ready.  I will create a new repository where I will work on UI.

If you are satisfied with the current state of this repository, could you please close this issue?

**Comment by PH-F** [comment]
Hallo Eddie,
All unittests work so yes, great job!
I'll wait until the UI is ready. And i will close this issue.
