### ISSUE TITLE
path

### ISSUE THREAD

**Issue by PH-F** [EddieMachete/rhi-core-isncsci-algorithm#2]
Hi Eddie,

I tested your code, works really good, great job!
I will try to implement this in our medical tool keeping the apache2 license in mind.

1 Small thing, in the files rhi-core-isncsci-algorithm-demo.html & rhi-core-isncsci-algorithm-demo-exam.html i changes the path from

<link rel="import" href="../../../rhi-core-isncsci-algorithm/master/rhi-core-isncsci-exam.html" />
<link rel="import" href="../../../rhi-core-isncsci-algorithm/master/rhi-core-isncsci-algorithm.html" />

to

<link rel="import" href="../rhi-core-isncsci-exam.html" />
<link rel="import" href="../rhi-core-isncsci-algorithm.html" />

otherwise a 404 occurs.

Thanks again.

**Comment by EddieMachete** [comment]
I don't see the paths posted in your message, but I'll have a look at them anyways.  Thanks for letting me know.

**Comment by EddieMachete** [comment]
By the way, would you be able to share some info on the application you are working on, maybe send me a direct message with some details?  I don't want to pester you if it is not possible but It helps me to show my bosses that the code is being used so that I can continue to work on this during the week and not just the weekends.  The details would only circulate internally at the Rich Hansen Institute.  We have a very strict [privacy policy](http://www.rickhanseninstitute.org/privacy-policy) here.

**Comment by PH-F** [comment]
I see ;- )
in the file rhi-core-isncsci-algorithm-demo.html there are 2 import like
../../../rhi-core-isncsci-algorithm/master/rhi-core-isncsci-exam.html

however these 2 files are located in the reporitory in ../rhi-core-isncsci-exam.html etc.

Just a minor thing.
I'll send you some info tomorrow morning by email.
